# Generated by Django 5.0.1 on 2026-06-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название участка')),
                ('short_name', models.CharField(max_length=20, verbose_name='Сокращение')),
                ('schedule_type', models.CharField(choices=[('5_2', '5/2 (Пн-Пт)'), ('2_2', '2/2 (сменный)')], default='5_2', max_length=10, verbose_name='Режим работы')),
                ('work_start', models.TimeField(default='08:00', verbose_name='Время начала смены')),
                ('work_end', models.TimeField(default='17:00', verbose_name='Время окончания смены')),
                ('hours_per_day', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Часов в день')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет для отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workstations', to='employees.employee', verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workstations', to='employees.employee', verbose_name='Кто редактировал')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное место работы')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='employees.employee', verbose_name='Кто создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_assignments', to='employees.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assignments', to='employees.employee', verbose_name='Кто редактировал')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='workstations.workstation', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Назначение на участок',
                'verbose_name_plural': 'Назначения на участки',
                'ordering': ['employee__last_name', 'workstation__name'],
                'unique_together': {('employee', 'workstation')},
            },
        ),
    ]
