# Generated by Django 6.0.6 on 2026-08-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['department__name', 'name'], 'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подразделения')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код подразделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workstations.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': ('Подразделение',),
                'verbose_name_plural': 'Подразделения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workstation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='workstations.department', verbose_name='Подразделение'),
        ),
    ]
