# Generated by Django 5.0.1 on 2026-06-22 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workstations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('weekend', 'Выходной'), ('sick', 'Больничный'), ('vacation', 'Отпуск')], default='present', max_length=20, verbose_name='Статус')),
                ('is_present', models.BooleanField(default=True, verbose_name='Был на работе')),
                ('is_weekend_shift', models.BooleanField(default=False, verbose_name='Работа в выходной')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('hours_norm', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Норма часов')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Переработка (часов)')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Фактические часы')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Кто редактировал')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstations.workstation', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Запись о работе',
                'verbose_name_plural': 'Записи о работе',
                'ordering': ['-record_date', 'employee__last_name', 'employee__first_name'],
                'unique_together': {('employee', 'record_date')},
            },
        ),
    ]
