# Generated by Django 6.0.6 on 2026-07-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('hours_norm', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Норма часов (40-чвсовая неделя)')),
            ],
            options={
                'verbose_name': 'Норма рабочего времени',
                'verbose_name_plural': 'Нормы рабочего времени',
                'ordering': ['-year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
