# Generated by Django 6.0.6 on 2026-07-28 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_vacantionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacantionRequest',
            new_name='VacationRequest',
        ),
    ]
