# Generated by Django 6.0.6 on 2026-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_vacationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='base_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Базовые часы (без переработки)'),
        ),
    ]
