# Generated by Django 6.0.6 on 2026-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyattendance_base_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название KPI')),
                ('type', models.CharField(choices=[('no_absence', 'Нет пропусков (любых)'), ('has_skills', 'Есть навыки'), ('overtime', 'Была переработка'), ('clean_workplace', 'Чистое рабочее место'), ('custom', 'Свой вариант')], default='custom', max_length=50, verbose_name='Тип KPI')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Бонус (руб.)')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Бонус (%) от оклада')),
                ('skill_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за навык (руб.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'Показатели KPI',
            },
        ),
    ]
