# Generated by Django 6.0.6 on 2026-08-10 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_kpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyworknorm',
            name='hours_norm',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Норма часов (40-часовая неделя)'),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базовый оклад')),
                ('kpi_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Бонус по KPI')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Итого зарплата')),
                ('kpi_details', models.JSONField(blank=True, default=dict, verbose_name='Детали KPI')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Рассчитано')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата расчета')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассчитал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись зарплаты',
                'verbose_name_plural': 'Записи зарплат',
                'ordering': ['-year', '-month', 'employee__last_name'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
