# Generated by Django 5.0.1 on 2026-06-22 08:52

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название навыка')),
                ('category', models.CharField(choices=[('production', 'Производство'), ('warehouse', 'Склад'), ('office', 'Офис')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('login', models.CharField(max_length=150, unique=True, verbose_name='Логин для входа')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Табельный номер')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер карточки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Может редактировать данные')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('registration_address', models.TextField(blank=True, verbose_name='Место регистрации')),
                ('residence_address', models.TextField(blank=True, verbose_name='Место проживания')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'В браке'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество детей')),
                ('military_status', models.CharField(blank=True, choices=[('liable', 'Военнообязанный'), ('not_liable', 'Не военнообязанный'), ('served', 'Отслужил'), ('exempt', 'Освобожден')], max_length=20, verbose_name='Военная обязанность')),
                ('education_specialty', models.CharField(blank=True, max_length=255, verbose_name='Специальность по образованию')),
                ('education_institution', models.CharField(blank=True, max_length=255, verbose_name='Где учился')),
                ('education_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('previous_work_1', models.TextField(blank=True, verbose_name='Предыдущее место работы 1')),
                ('previous_work_2', models.TextField(blank=True, verbose_name='Предыдущее место работы 2')),
                ('previous_work_3', models.TextField(blank=True, verbose_name='Предыдущее место работы 3')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Кто редактировал')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('middle', 'Средний'), ('expert', 'Эксперт')], default='middle', max_length=20, verbose_name='Уровень')),
                ('certified_date', models.DateField(auto_now_add=True, verbose_name='Дата получения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_employees', to='employees.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Квалификация сотрудника',
                'verbose_name_plural': 'Квалификации сотрудников',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
