# Generated by Django 5.0.1 on 2026-06-18 14:17

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Табельный номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Может редактировать данные')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronomic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('registration_address', models.TextField(blank=True, verbose_name='Место регистрации')),
                ('residence_address', models.TextField(blank=True, verbose_name='Место проживания')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'В брае'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество детей')),
                ('military_status', models.CharField(blank=True, choices=[('liable', 'Военнообязанный'), ('not_liable', 'Не военнообязанный'), ('served', 'Отслужил'), ('exempt', 'Освобожден')], max_length=20, verbose_name='Военная обязанность')),
                ('education_specialty', models.CharField(blank=True, max_length=255, verbose_name='Спецциальность по образованию')),
                ('education_institution', models.CharField(blank=True, max_length=255, verbose_name='Где учился')),
                ('education_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('previous_work_1', models.TextField(blank=True, verbose_name='Предыдущее место работы 1')),
                ('previous_work_2', models.TextField(blank=True, verbose_name='Предыдущее место работы 2')),
                ('previous_work_3', models.TextField(blank=True, verbose_name='Предыдущее место работы 3')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
