# Generated by Django 5.0.1 on 2026-06-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер карточки'),
        ),
    ]
