# Generated by Django 5.0.1 on 2026-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='patronomic',
            new_name='patronymic',
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_specialty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специальность по образованию'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'В браке'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение'),
        ),
    ]
