# Generated by Django 6.0.6 on 2026-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базовый оклад (руб.)'),
        ),
    ]
