# Generated by Django 6.0.6 on 2026-08-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_base_salary'),
        ('workstations', '0002_alter_workstation_options_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='workstations.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('director', 'Директор'), ('deputy', 'Заместитель')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
